import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import numpy.random as nr
import time
from tqdm import tqdm
import copy

from src.network_model import NetworkModel, get_mat_f_q_from_covariance
from src.preprocess import preprocess_df


def generate_random_mvn_model(n_entity=5, n_sample=1000, seed=None):
    """Generates a multivariate normal model with a random covariance matrix"""
    if seed:
        nr.seed(seed)
    mu = nr.rand(n_entity)
    mat_a_rand = nr.rand(n_entity, n_entity)
    rand_cov = np.dot(mat_a_rand, mat_a_rand.T)
    samples = nr.multivariate_normal(mu, rand_cov, size=n_sample)
    data_df = pd.DataFrame(samples, columns=list(range(n_entity)))
    return data_df, rand_cov


def samples2flows(data_df, max_flow_per_sample=10, min_flow_per_sample=5, max_flow_sep=0.4, min_flow_sep=0.2,
                  ref_time=np.datetime64('2023-06-06'), src_feature_col=' Total Fwd Packets',
                  dst_feature_col=' Total Backward Packets', date_col=' Timestamp', src_id_col=' Source IP',
                  dst_id_col=' Destination IP'):
    """
    Converts samples on entities to collection of flows where each flow is generated by randomly picking two entities
    with their samples assigned as directional flow features. Random flows are separated by realizations from uniform
    distribution

    :param data_df: DataFrame of entity-wise samples
    :param max_flow_per_sample: Maximum number of flows generated from same entity sample
    :param min_flow_per_sample: Minimum number of flows generated from same entity sample
    :param max_flow_sep: Maximum time interval between consecutive flows (in seconds)
    :param min_flow_sep: Minimum time interval between consecutive flows (in seconds)
    :param ref_time: Starting datetime of flows
    :param src_feature_col: Flow data DataFrame column name indicating the source entity of the flow
    :param dst_feature_col: Flow data DataFrame column name indicating the destination entity of the flow
    :param date_col: Flow data DataFrame column name indicating the starting datetime of the flow
    :param src_id_col: Column name of the flows data DatatFrame that identifies the source entity.
    :param dst_id_col: Column name of the flows data DatatFrame that identifies the destination entity.
    :return:
        flow_df: DataFrame containing flows
    """

    m, n = data_df.shape
    flow_df = pd.DataFrame()
    t = copy.copy(ref_time)
    for i in tqdm(range(m)):
        n_flow = np.random.choice(range(min_flow_per_sample, max_flow_per_sample+1), size=1)[0] + 1
        for _ in range(n_flow):
            src, dst = np.random.choice(range(n), size=2, replace=False)
            dt = np.timedelta64(int(np.random.uniform(min_flow_sep, max_flow_sep) * 1000), 'ms')
            t += dt
            temp_df = pd.DataFrame({date_col: t, src_id_col: src, dst_id_col: dst,
                                    src_feature_col: data_df.iloc[i, src],
                                    dst_feature_col: data_df.iloc[i, dst]}, index=[0])
            flow_df = pd.concat((flow_df, temp_df), ignore_index=True)
    return flow_df


if __name__ == '__main__':  # TODO: Add test for connection size windowing
    start = time.time()
    samples_df, cov = generate_random_mvn_model(n_entity=5, n_sample=10_000)
    f_test, _ = get_mat_f_q_from_covariance(cov)

    # Test with different parameters. 100 samples per flow give negligible error
    # Convergence is observed. TODO: Gather error w.r.t parameter space
    df_raw = samples2flows(samples_df, max_flow_sep=0.4, min_flow_per_sample=5, max_flow_per_sample=10)
    df = preprocess_df(df_raw, date_col=' Timestamp')

    print(df)
    end = time.time()
    print('File to df time (s): ', end - start)

    start = time.time()
    nm = NetworkModel()
    nm.read_flows(df, entity_names=list(np.arange(5)), conn_param=None, window_type='time', sync_window_size=20,
                  time_scale='sec')
    end = time.time()
    print('\nDf to samples time (s): ', end - start, '\n')

    start = time.time()
    nm.fit_graph_model()
    nm.plot_f()
    end = time.time()
    print('\nSamples to Graph time (s): ', end - start)
    plt.title('Fitted Matrix F')

    print('\nNumber of Samples in Fitting:', nm.samples.shape[0])

    plt.matshow(f_test)
    plt.colorbar()
    plt.title('True Graph Matrix')

    plt.matshow(cov)
    plt.colorbar()
    plt.title('True Covariance')

    plt.show()
